### ISSUE TITLE
How to get status of coroutine?

### ISSUE THREAD

**Issue by ib00** [slembcke/Tina#6]
Is it possible to get a status of coroutine (running, suspended, dead, etc.)?

**Comment by slembcke** [comment]
Partially. I have a `tina.completed` bool that tracks completion (dead), but that's it: https://github.com/slembcke/Tina/blob/master/tina.h#L52 Though not intended to be public state, `tina._caller` will be non-NULL when a coroutine is running.

I've also kept the code for tina.h to be as short as possible. (It's only about ~50 lines of actual C code) I like libraries that are simple enough to be easily modified, and wanted to encourage that with Tina.
