### ISSUE TITLE
MSVC fixes

### ISSUE THREAD

**Issue by slembcke** [slembcke/Tina#7]
Two new issues seem to have come up in newer versions of MSVC++:
* The C99 initializer list style I was using doesn't work anymore. (ex: `foo = (bar){.a = 1, .b = 2}`)
* It no longer allows casting non-function pointers to function pointers for the asm blob.

Should be fixed via https://github.com/slembcke/Tina/commit/0e57681597f9e4d2aa1e5b7c03800c412b7b016c

**Comment by Dunk-Master** [comment]
its fixed 🍺

**Comment by Dunk-Master** [comment]
I tried removing the tina_func* to std::function but couldn't. I think this is digestable for beginners https://godbolt.org/z/rbexobneW 
 🍺

**Comment by slembcke** [comment]
The assembly code can call the tina_func* because it's just a function pointer. Calling a std::func from assembly is not really possible without writing different assembly code for every compiler/version, and even then it would be complicated. You might as well just call a C function that calls your std::func.
